---
functional:
  - Пользователь должнен иметь возможность регистрации
  - Пользователь должен иметь возможность создания игры "Create game" (выбор языка позже)
  - При создании игры с другим пользователем, пользователь находится в режиме ожидания второго игрока
  - При создании игры с другим пользователем игра высвечивается как "доступная для подключения" у других пользователей
  - При нажатии "Fight" обоих перебрасывает в игру
  - Каждый игрок должен видеть код своего соперника в режиме он-лайн
  - Каждый игрок должен видеть задание
  - Каждый игрок должен имееть кнопку "check" для проверки своего решения
  - Количество попыток проверки должно быть неограниченно
  - Если вдруг один из игроков вылетел из игры, второй должен иметь возможность продолжать играть
  - Если вдруг один из игроков вылетел из игры - он в любой момент игры, пока она не закончена, может переподключиться в игру
  - Когда игрок находит верное решение должно высвечиваться модальное окно о победе
  - Когда соперник решил задание первым - должно высвечиваться модальное окно о поражении
  - Победитель-игрок должен иметь возможность выйти из игры по нажатию кнопки "back to home"
  - После поражения игрок должен иметь возможность остаться и доиграть до конца
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Наверху должно находиться время игры
  - После победы игрок должен иметь возможность остаться и посмотреть ещё раз на свой код
implicit:
  - Пользователь должен иметь возможность сыграть пробную игру, без регистрации
  - Пользователь должен иметь возможность прикрепить к аккаунту Github
  - Пользователь должен иметь возможность прикрепить к аккаунту Discord
  - Пользователь должен иметь возможность входа по логину
  - Пользователь должен иметь возможность входа по Github
  - Пользователь должен иметь возможность входа по Discord
  - Пользователь должен иметь возможность просматривать таблицу лидеров
  - Пользователь должен иметь возможность просматривать турнирную таблицу
  - Пользователь должен иметь возможность просматривать историю игр
  - Пользователь должен иметь возможность просматривать свой профиль
  - Пользователь должен иметь возможность настройки профиля
  - Пользователь должен иметь возможность ввода кода в окне решения задания
  - Пользователь должен иметь возможность выбора сложности игры
  - Пользователь должен иметь возможность выбора задания
  - Пользователь должен иметь возможность выбора языка написания решения 
  - Пользователь должен иметь возможность выбора задания по категории
  - Пользователь должен иметь возможность подключиться к игре, которая высвечивается как "доступная для подключения"
  - Пользователь должен иметь возможность сдаться
